clear all;
close all;
% 
% syms A x;
% f = A * cosh (x / A);
% f1 = sinh(x / A);
% 
% syms Fy1 Fwind;
% xupper = A*asinh(Fy1/Fwind);
% fupper = subs(f, x, xupper);
% 
% syms x0 Length
% xlower = -A*asinh((Length - (A*Fy1)/Fwind)/A);
% flower = subs(f, x, xlower);

syms Ggg Fgg ...
    l ...
    theta5 theta4 theta3 theta2 theta1 ...
    Gsb Fsb ...
    Fy1 Gball ...
    Fwind;
U = (Ggg - Fgg) * (0.5 * l * cos(theta5)) ...
    + (Ggg - Fgg) * (l * cos(theta5) + 0.5 * l * cos(theta4)) ...
    + (Ggg - Fgg) * (l * cos(theta5) + l * cos(theta4) + 0.5 * l * cos(theta3)) ...
    + (Ggg - Fgg) * (l * cos(theta5) + l * cos(theta4) + l * cos(theta3) + 0.5 * l * cos(theta2)) ...
    + (Gsb - Fsb) * (l * cos(theta5) + l * cos(theta4) + l * cos(theta3) + l * cos(theta2) + 0.5 * l * cos(theta1)) ...
    + (Fy1 + Gball) * (l * cos(theta5) + l * cos(theta4) + l * cos(theta3) + l * cos(theta2) + l * cos(theta1)) ...
    + Fwind * l * (sin(theta5) + sin(theta4) + sin(theta3) + sin(theta2) + sin(theta1));

U1 = diff(U, 'theta1');
U2 = diff(U, 'theta2');
U3 = diff(U, 'theta3');
U4 = diff(U, 'theta4');
U5 = diff(U, 'theta5');
