% global alpha beta1 beta2 beta3 beta4 beta5 beta6 beta7;
global Gball Vwind;
% global Depth g l lamda Length mfb mgg msb rfb rgg rsb rouwater;
% global F1 F2 G1 G2 Gfb;
global H;
% global A;
global FWIND;
global Fy3;
global s1 s2 xHorizon;
global theta1 theta2 theta3 theta4 theta5 thetaCa thetaMao;
% global x0 x1;
global xupper yupper;
global HorizonFlag SinkFlag;